// RoadSeg builder tests. Synthetic fixtures lock each block's CreateRoadSegment
// port (src/render/road-build.ts); a final smoke block runs the REAL level 0
// (data/ is gitignored + regenerated by bootstrap) end-to-end through the
// projection (road-build → road-projection). Fidelity vs the original is a later
// visual road-parity check (the field-golden harness is blocked on boot coupling).
import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { buildRoadSegs, parseParams, ROAD_BUILD_DEFAULTS, type RoadBlockRaw } from "../../src/render/road-build";
import { buildDrawSegs, ROAD_DEFAULTS, type Camera3D } from "../../src/render/road-projection";

const C = { globalCurve: 0.1, globalHill: 0.9, numLaps: 1 };
const ident = (n: string) => parseInt(n.replace(/\D/g, ""), 10) || 0;
const block = (btype: string, z: number, dist: number, params: string): RoadBlockRaw => ({ btype, z, dist, active: true, params });

// no surface/edge defs needed for geometry-only fixtures
const surf = (n: string) => ident(n);
const edge = (n: string) => ident(n);
const hasEdge = () => true;

describe("parseParams", () => {
  it("k=v CSV + bare flags", () => {
    expect(parseParams("a=1,b=2,flag")).toEqual({ a: "1", b: "2", flag: "true" });
    expect(parseParams("")).toEqual({});
  });
});

describe("bend → changeX (flat, ramp is dead code)", () => {
  it("changeX = bend_curve * bendMultiplier * globalCurve, flat over the range", () => {
    const segs = buildRoadSegs(
      [block("levelinfo", 0, 100, "levelinfo_bendmultiplier=2"), block("bend", 0, 50, "bend_curve=3")],
      surf, edge, hasEdge, C,
    );
    // 3 * 2 * 0.1 = 0.6, identical for every covered seg (no ramp)
    for (let z = 0; z < 50; z++) expect(segs[z].changeX).toBeCloseTo(0.6, 9);
  });
});

describe("width → set + back-ramp over changeDist", () => {
  it("sets width over [z0,z1) and linearly ramps in over changeDist before z0", () => {
    // first block establishes width 100 at [0,100); second sets 300 at [100,200) with ramp 50
    const segs = buildRoadSegs(
      [block("width", 0, 100, "width_width=100,width_changeDist=0"),
       block("width", 100, 100, "width_width=300,width_changeDist=50")],
      surf, edge, hasEdge, C,
    );
    expect(segs[100].width).toBe(300);
    expect(segs[199].width).toBe(300);
    // ramp region [50,100): from 100 → 300 linearly
    expect(segs[50].width).toBeCloseTo(100, 6);
    expect(segs[75].width).toBeCloseTo(200, 6); // midpoint
    expect(segs[99].width).toBeGreaterThan(290);
  });
});

describe("abshill → changeY + accumulating lastHillAngle", () => {
  it("changeY = ((angle-lastAngle)/len)*globalHill; lastAngle accumulates across blocks", () => {
    const segs = buildRoadSegs(
      [block("abshill", 0, 100, "hill_angle=10"),     // slope = 10/100 = 0.1
       block("abshill", 100, 100, "hill_angle=10")],  // slope = (10-10)/100 = 0 (already there)
      surf, edge, hasEdge, C,
    );
    for (let z = 0; z < 100; z++) expect(segs[z].changeY).toBeCloseTo(0.1 * 0.9, 9);
    for (let z = 100; z < 200; z++) expect(segs[z].changeY).toBeCloseTo(0, 9);
  });
});

describe("surface / edge", () => {
  it("surface sets surfaceIndex; edge sets col + edgeIndex per side", () => {
    const segs = buildRoadSegs(
      [block("surface", 0, 50, "surface_type=road_4"),
       block("edge", 0, 50, "edge_side=left,edge_type=edge_sand2"),
       block("edge", 0, 50, "edge_side=right,edge_type=edge_grass1")],
      (n) => (n === "road_4" ? 3 : 0),
      (n) => (n === "edge_sand2" ? 7 : n === "edge_grass1" ? 1 : 0),
      hasEdge, C,
    );
    expect(segs[10].surfaceIndex).toBe(3);
    expect(segs[10].colL >>> 0).toBe(0xffffffff);
    expect(segs[10].edgeIndexL).toBe(7);
    expect(segs[10].colR >>> 0).toBe(0xffffffff);
    expect(segs[10].edgeIndexR).toBe(1);
  });
  it("edge with missing def is skipped", () => {
    const segs = buildRoadSegs([block("edge", 0, 50, "edge_side=both,edge_type=nope")], surf, () => 0, () => false, C);
    expect(segs[10].colL).toBe(0);
    expect(segs[10].edgeIndexL).toBe(0);
  });
});

describe("laps", () => {
  it("numLaps doubles the segment count and repeats the layout", () => {
    const blocks = [block("bend", 0, 100, "bend_curve=1")];
    const one = buildRoadSegs(blocks, surf, edge, hasEdge, { ...C, numLaps: 1 });
    const two = buildRoadSegs(blocks, surf, edge, hasEdge, { ...C, numLaps: 2 });
    expect(two.length).toBe(one.length * 2);
    expect(two[150].changeX).toBeCloseTo(two[50].changeX, 9); // lap 2 mirrors lap 1
  });
});

// ── real-data smoke: level 0 end-to-end (build → project) ────────────────────
const here = dirname(fileURLToPath(import.meta.url));
const levelsPath = join(here, "..", "..", "data", "levels.json");
const roaddataPath = join(here, "..", "..", "data", "roaddata.json");

describe("real level 0 (smoke; needs data/)", () => {
  it.runIf(existsSync(levelsPath) && existsSync(roaddataPath))(
    "builds level 0 and projects a sane road",
    () => {
      const levels = JSON.parse(readFileSync(levelsPath, "utf8"));
      const roaddata = JSON.parse(readFileSync(roaddataPath, "utf8"));
      const lv = levels[0];
      const surfaceIdx = new Map<string, number>(roaddata.roadsurfaces.map((s: any, i: number) => [s.name, i]));
      const edgeIdx = new Map<string, number>(roaddata.edgesegments.map((e: any, i: number) => [e.name, i]));

      const segs = buildRoadSegs(
        lv.road.blocks,
        (n) => surfaceIdx.get(n) ?? 0,
        (n) => edgeIdx.get(n) ?? 0,
        (n) => edgeIdx.has(n),
        ROAD_BUILD_DEFAULTS, // 2 laps
      );

      const lapLength = Math.max(...lv.road.blocks.map((b: any) => +b.z + +b.dist));
      expect(segs.length).toBe(lapLength * 2);
      // the track has real curves, hills, widths, surfaces, edges
      expect(segs.some((s) => s.changeX !== 0)).toBe(true);
      expect(segs.some((s) => s.changeY !== 0)).toBe(true);
      expect(segs.every((s) => s.width >= 0)).toBe(true);
      expect(segs.some((s) => s.width > 0)).toBe(true);
      expect(segs.some((s) => s.colL !== 0 || s.colR !== 0)).toBe(true);

      // feed P2: project from the start with the camera slightly above the road
      const cam: Camera3D = { x: 0, y: 30, z: 0 };
      const proj = buildDrawSegs(segs, cam, ROAD_DEFAULTS, 640, 480);
      expect(proj.count).toBeGreaterThan(0);
      // every projected seg is finite; nearest is wider than a far one (perspective)
      expect(proj.drawSegs.every((d) => Number.isFinite(d.x0) && Number.isFinite(d.ypos))).toBe(true);
      const wNear = proj.drawSegs[1].x1 - proj.drawSegs[1].x0;
      const wFar = proj.drawSegs[50].x1 - proj.drawSegs[50].x0;
      expect(wNear).toBeGreaterThan(wFar);
    },
  );
});
