// Game data-loader tests. These are NOT bit-exact physics gates — they verify the
// loaders apply the EXACT AS3 conversions (XmlHelper.GetAttr*, Vars decode, GetParams)
// to the raw-string JSON. Inline fixtures keep the suite portable (data/ is gitignored
// and regenerated by bootstrap); a final smoke block runs over the real data/ if present.
import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { str, num, int, bool, parseParams } from "../../src/game/util/convert";
import { loadMaterials } from "../../src/game/data/materials";
import { Vars } from "../../src/game/data/vars";
import { loadLevels } from "../../src/game/data/levels";

describe("convert — AS3-faithful GetAttr*", () => {
  it("num = Number() with absent→default", () => {
    expect(num("1.5")).toBe(1.5);
    expect(num("")).toBe(0); // Number("") === 0
    expect(num(undefined, 7)).toBe(7);
  });
  it("int = int() truncate-toward-zero, NaN→0", () => {
    expect(int("1.9")).toBe(1);
    expect(int("-1.9")).toBe(-1);
    expect(int("abc")).toBe(0);
    expect(int(undefined, 5)).toBe(5);
  });
  it("str/bool", () => {
    expect(str(undefined, "d")).toBe("d");
    expect(bool("true")).toBe(true);
    expect(bool("false")).toBe(false); // ONLY "true" is truthy
    expect(bool(undefined, true)).toBe(true);
  });
  it("parseParams — split ',' then '=', bare key → true", () => {
    const p = parseParams("bend_curve=0,solidedge,ai_max=6");
    expect(p.get("bend_curve")).toBe("0");
    expect(p.get("solidedge")).toBe(true);
    expect(p.get("ai_max")).toBe("6");
    expect(parseParams("").size).toBe(0);
    expect(parseParams(null).size).toBe(0);
  });
});

describe("loaders — inline fixtures", () => {
  it("materials → numeric fixture presets", () => {
    const lib = loadMaterials({ hinge: { density: "0.26", friction: "1", restitution: "0.1" } });
    expect(lib.get("hinge")).toEqual({ density: 0.26, friction: 1, restitution: 0.1 });
  });

  it("vars — typed getters + array split + unknown throws", () => {
    const v = new Vars([
      { name: "road_global_curve", type: "number", value: "0.1" },
      { name: "nitro_arc", type: "array", value: "-0.5, -0.3, 0.2" },
    ]);
    expect(v.getNumber("road_global_curve")).toBe(0.1);
    expect(v.getArray("nitro_arc")).toEqual(["-0.5", " -0.3", " 0.2"]);
    expect(v.getNumberArray("nitro_arc")).toEqual([-0.5, -0.3, 0.2]);
    expect(v.has("road_global_curve")).toBe(true);
    expect(() => v.getNumber("nope")).toThrow();
  });

  it("levels — blocks, params, checkpoints, medals", () => {
    const lv = loadLevels([
      {
        id: "1",
        name: "COAST",
        displayname: "COAST",
        category: "0",
        desc: "",
        bg: "1",
        heatrush: { gold: "70", silver: "80", bronze: "90" },
        road: {
          randseed: "11111111",
          blocks: [
            { btype: "bend", id: "-1", z: "0", dist: "1533", active: "true", params: "bend_curve=0" },
            { btype: "surface", id: "-1", z: "0", dist: "1175", active: "true", params: "surface_type=road_1" },
          ],
          objs: [
            { columnid: "0", id: "", type: "obj_checkpoint_start", x: "0", z: "399.8", rot: "NaN", scale: "1", params: "editor_layer=1" },
          ],
        },
        joints: [],
        map: null,
      },
    ]);
    expect(lv[0].name).toBe("COAST");
    expect(lv[0].bg).toBe(1);
    expect(lv[0].medals).toEqual({ gold: 70, silver: 80, bronze: 90 });
    expect(lv[0].blocks.map((b) => b.btype)).toEqual(["bend", "surface"]);
    expect(lv[0].blocks[0].params.get("bend_curve")).toBe("0");
    expect(lv[0].blocks[1].params.get("surface_type")).toBe("road_1");
    expect(lv[0].checkpoints[0].type).toBe("obj_checkpoint_start");
    expect(Number.isNaN(lv[0].checkpoints[0].rot)).toBe(true); // rot="NaN" preserved
  });
});

// Smoke test over the REAL extracted data, only when present (data/ is gitignored).
const dataDir = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "data");
const haveData = existsSync(join(dataDir, "materials.json"));
const read = (f: string) => JSON.parse(readFileSync(join(dataDir, f), "utf8"));

describe.skipIf(!haveData)("real data/ smoke", () => {
  it("16 materials (hinge correct), 119 vars, 8 levels with COAST", () => {
    const ml = loadMaterials(read("materials.json"));
    expect(ml.size).toBe(16);
    expect(ml.get("hinge")).toEqual({ density: 0.26, friction: 1, restitution: 0.1 });

    const varsJson = read("vars.json");
    expect(varsJson.length).toBe(119);
    const v = new Vars(varsJson);
    expect(v.getNumber("road_global_curve")).toBeCloseTo(0.1, 12);

    const lv = loadLevels(read("levels.json"));
    expect(lv.length).toBe(8);
    expect(lv.map((l) => l.name)).toContain("COAST");
    // every block's params parse without throwing
    const totalBlocks = lv.reduce((n, l) => n + l.blocks.length, 0);
    expect(totalBlocks).toBeGreaterThan(500);
  });
});
